server {
    listen 80;
    server_name localhost;

    # Frontend Static Files
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Backend Proxy
    location /api/ {
        resolver 127.0.0.11 valid=30s;
        set $paxel_backend 'http://${PAXEL_HOST}:8888';
        rewrite ^/api/(.*) /$1 break;
        proxy_pass $paxel_backend;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        
        # Security & Limits
        client_max_body_size 5M;
        proxy_read_timeout 300s;
    }

    # Error handling
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
