services:
  hotpaxel:
    image: hotpaxel/hotpaxel:0.2.1-alpha.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:80"   # UI (Nginx)
      - "8889:8888" # API (Axum)
    environment:
      - ENABLE_UI=true
      - PAXEL_API=http://localhost:8888
    restart: always
