services:
  hotpaxel:
    image: hotpaxel/hotpaxel:0.2.1-alpha.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888" # Unified Port (API + UI)
    environment:
      - PORT=8888
      - STATIC_DIR=./public
      - DISABLE_UI=false
    restart: always
